name: partlog
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  rename: ^2.1.1
  dio: ^5.3.2
  get_it: ^7.6.0
  equatable: ^2.0.5
  fluttertoast: ^8.2.2
  iconsax: ^0.0.8
  logger: ^1.1.0
  lottie: ^3.0.0
  flutter_easyloading: ^3.0.5
  animations: ^2.0.11

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - asset/lottie/
    - asset/images/
    - asset/images/rm251-mind-08-f.jpg
    - asset/images/rm222-mind-14.jpg
    - asset/svg/
    - asset/icon/
    - asset/lottie/spinner_animation.json
    - asset/pdf/

